
SELECT * FROM pizza_sales

--Total Revenue generated by pizza sales
SELECT ROUND(SUM(total_price), 2) TotalRevenue
FROM pizza_sales;

--Average amount spent per order
SELECT ROUND(SUM(total_price)/COUNT(DISTINCT order_id),2) AvgOrderValue
FROM pizza_sales;

--Total pizzas sold
SELECT  SUM(quantity) TotalPizzaSold
FROM pizza_sales

--Total number of orders placed
SELECT COUNT(DISTINCT order_id) TotalOrders
FROM pizza_sales

--Total number of pizzas ordered per order
SELECT order_id, SUM(quantity) PizzaQuantity
FROM pizza_sales
Group by order_id
Order by order_id

--Average number of pizzas ordered per order
SELECT Cast(Cast(SUM(quantity) AS DECIMAL (10,2))/CAST(Count(DISTINCT order_id)AS DECIMAL (10,2))AS INT ) AvgPizzaOrdered
FROM pizza_sales

